export enum SCREEN {
  LOGIN = 'LOGIN',
  SIGN_UP = 'SIGN_UP',
  VERIFY = 'VERIFY',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  NEW_PASSWORD = 'NEW_PASSWORD',

  HOME = 'HOME',
  SEARCH = 'SEARCH',
  PET_CARE_VIDEOS = 'PET_CARE_VIDEOS',
}
